Repository BusanBubu99/WorkoutWith, pull requests merged in 2022-09, with the labels that each got.

#8 Implement authentication api
  server/WorkoutWithServer/settings.py
  server/WorkoutWithServer/urls.py
  server/accounts/__init__.py
  server/accounts/admin.py
  server/accounts/apps.py
  server/accounts/managers.py
  server/accounts/migrations/__init__.py
  server/accounts/models.py
  server/accounts/tests.py
  server/accounts/urls.py
  server/accounts/views.py
Labels: implementation, REST

#9 fix error related with CSRF Token
  server/WorkoutWithServer/settings.py
Labels: bug, REST

#7 Add api of user profile
  server/WorkoutWithServer/settings.py
  server/WorkoutWithServer/urls.py
  server/userprofile/__init__.py
  server/userprofile/admin.py
  server/userprofile/apps.py
  server/userprofile/migrations/__init__.py
  server/userprofile/models.py
  server/userprofile/serializers.py
  server/userprofile/tests.py
  server/userprofile/urls.py
  server/userprofile/views.py
Labels: implementation, REST

#10 Add email verification
  server/.gitignore
  server/WorkoutWithServer/settings.py
  server/accounts/urls.py
  server/accounts/views.py
Labels: implementation, REST

#11 fix authentication error related with sessionAuth
  server/WorkoutWithServer/settings.py
Labels: bug, REST

#16 Server matching
  server/WorkoutWithServer/settings.py
  server/WorkoutWithServer/urls.py
  server/matching/__init__.py
  server/matching/admin.py
  server/matching/apps.py
  server/matching/migrations/__init__.py
  server/matching/models.py
  server/matching/serializers.py
  server/matching/tests.py
  server/matching/urls.py
  server/matching/views.py
  server/userprofile/serializers.py
Labels: implementation, REST, work in progress
